stages:
  - build
  - deploy

build-job:
  stage: build
  before_script:
    - cp ${PROD_ENV} .env
    - cp ${TEST_ENV} .env-test
  script:
    - docker build -t booking-api-image .

deploy-job:
  stage: deploy
  script:
    - docker compose -f ./infra/docker-compose.ci.yml up -d
