stages:
  - build
  - lint_format
  - migrations
  - test
  - deploy

build-job:
  stage: build
  before_script:
    - cp ${PROD_ENV} .env
    - cp ${TEST_ENV} .env-test
  script:
    - docker build -t booking-api-image .

lint-job:
  stage: lint_format
  script:
    - docker run --rm booking-api-image uv run ruff check

format-job:
  stage: lint_format
  script:
    - docker run --rm booking-api-image uv run ruff format --check

migrations-job:
  stage: migrations
  script:
    - docker run --rm --network myNetwork booking-api-image uv run alembic upgrade head

test-job:
  stage: test
  script:
    - docker-compose -f infra/docker-compose.yml -f infra/docker-compose.test.yml up --abort-on-container-exit

deploy-job:
  stage: deploy
  script:
    - docker compose -f ./infra/docker-compose.ci.yml up -d
