stages:
  - build
  - deploy

build-job:
  stage: build
  before_script:
    - cp ${PROD_ENV} .env
    - cp ${TEST_ENV} .env-test
    - echo "$JWT_PRIVATE_KEY" > ./src/certs/jwt/private.pem
    - echo "$JWT_PUBLIC_KEY" > ./src/certs/jwt/public.pem
  script:
    - docker build -t booking-api-image .
    - docker build -t booking-nginx-image ./nginx

deploy-job:
  stage: deploy
  script:
    - docker compose -f ./infra/docker-compose.ci.yml up -d
