stages:
  - prepare-job
  - build
  - lint_format
  - migrations
  - tests
  - deploy

prepare-job:
  stage: prepare
  script:
    - echo "$PROD_ENV" > .env
    - echo "$TEST_ENV" > .env-test
    - mkdir -p ./src/certs/jwt
    - echo "$JWT_PRIVATE_KEY" > ./src/certs/jwt/private.pem
    - echo "$JWT_PUBLIC_KEY" > ./src/certs/jwt/public.pem
  artifacts:
    paths:
      - .env
      - .env-test
      - ./src/certs/

build-job:
  stage: build
  script:
    - docker build -t booking-api-image .
    - docker build -t booking-nginx-image ./nginx

lint-job:
  stage: lint_format
  script: docker run --rm booking-api-image uv run ruff check

format-job:
  stage: lint_format
  script: docker run --rm booking-api-image uv run ruff format --check

migrations-job:
  stage: migrations
  script: docker run --rm booking-api-image uv run alembic upgrade head

tests-job:
  stage: tests
  script: docker-compose -f infra/docker-compose.yml -f infra/docker-compose.test.yml up --build --abort-on-container-exit

deploy-job:
  stage: deploy
  script:
    - docker compose -f ./infra/docker-compose.ci.yml up -d
