[project]
name = "fastapi-learn"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.12.0",
    "black>=25.1.0",
    "fastapi[standard,standart]>=0.115.12",
    "pydantic>=2.11.5",
    "uvicorn>=0.34.2",
]
