services:
#  api:
#    build:
#      context: ../
#    container_name: booking-api
#    command: ./infra/commands/api.sh
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db

  db:
    image: postgres:17
    container_name: booking-db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env

volumes:
  postgres_data: