services:
  api:
    container_name: booking-api-test
    command: ./infra/commands/test-api.sh
    env_file:
      - ../.env-test
    ports:
      - "8001:8000"
    volumes:
      - booking_static_test:/app/src/static/

  db:
    container_name: booking-db-test
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    env_file:
      - ../.env-test

  celery:
    container_name: booking-celery-test
    env_file:
      - ../.env-test
    volumes:
      - booking_static_test:/app/src/static/

  beat:
    container_name: booking-celery-beat-test
    env_file:
      - ../.env-test
    volumes:
      - booking_static_test:/app/src/static/


  redis:
    container_name: booking-redis-test
    ports:
      - "6380:6379"

volumes:
  postgres_data_test:
  booking_static_test: