services:
  api:
    build:
      context: ../
    container_name: booking-api
    command: ./infra/commands/api.sh
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:17
    container_name: booking-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env

  redis:
    image: redis:7.4.4
    container_name: booking-redis
    ports:
      - "6379:6379"


volumes:
  postgres_data: