services:
  api:
    build:
      context: ../
    container_name: booking-api
    command: ./infra/commands/api.sh
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    volumes:
      - booking-static:/app/src/static/
    depends_on:
      - db
      - redis

  db:
    image: postgres:17
    container_name: booking-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env

  celery:
    build:
      context: ../
    container_name: booking-celery
    command: [ "./infra/commands/celery.sh", "celery" ]
    env_file:
      - ../.env
    volumes:
      - booking-static:/app/src/static/
    depends_on:
      - redis

  beat:
    build:
      context: ../
    container_name: booking-celery-beat
    command: [ "./infra/commands/celery.sh", "beat" ]
    env_file:
      - ../.env
    volumes:
      - booking-static:/app/src/static/
    depends_on:
      - celery

  flower:
    build:
      context: ../
    container_name: flower
    env_file:
      - ../.env
    command: [ "./infra/commands/celery.sh", "flower" ]
    ports:
      - "5555:5555"
    depends_on:
      - celery

  redis:
    image: redis:7.4.4
    container_name: booking-redis


volumes:
  postgres_data:
  booking-static: