services:
  api:
    image: booking-api-image:latest
    container_name: booking-api-test
    command: ./infra/commands/test-api.sh
    env_file:
      - ../.env-test
    volumes:
      - ../src/certs/jwt/private.pem:/app/src/certs/jwt/private.pem:ro
      - ../src/certs/jwt/public.pem:/app/src/certs/jwt/public.pem:ro
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      celery:
        condition: service_started
    networks:
      - booking-backend-tier

  db:
    image: postgres:17
    container_name: booking-db-test
    env_file:
      - ../.env-test
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - booking-backend-tier

  redis:
    image: redis:7.4.4
    container_name: booking-redis-test
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - booking-backend-tier

  celery:
    image: booking-api-image:latest
    container_name: booking-celery-test
    command: [ "./infra/commands/celery.sh", "celery" ]
    env_file:
      - ../.env-test
    volumes:
      - ../src/certs/jwt/private.pem:/app/src/certs/jwt/private.pem:ro
      - ../src/certs/jwt/public.pem:/app/src/certs/jwt/public.pem:ro
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - booking-backend-tier

  beat:
    image: booking-api-image:latest
    container_name: booking-celery-beat-test
    command: [ "./infra/commands/celery.sh", "beat" ]
    env_file:
      - ../.env-test
    volumes:
      - ../src/certs/jwt/private.pem:/app/src/certs/jwt/private.pem:ro
      - ../src/certs/jwt/public.pem:/app/src/certs/jwt/public.pem:ro
    depends_on:
      celery:
        condition: service_started
    networks:
      - booking-backend-tier


volumes:
  postgres_data_test:

networks:
  booking-backend-tier:
    driver: bridge